import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Router } from "next/navigation";
import LogoutButton from "@/components/LogoutButton";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100">
        <nav className="bg-blue-600 text-white p-4 flex justify-between">
          <h1 className="text-xl font-bold">QuickCart</h1>
          <div className="space-x-4">
            <LogoutButton/>
          </div>
        </nav>

        <main className="p-6">{children}</main>
      </body>
    </html>
  );
}
